version: '3.7'

services: 
  ring:
    container_name: 'ring'
    build: 
      context: './docker-file/react'
    image: node_16.13.1_react
    volumes: 
      - ../ring:/usr/src/app
    ports:
      - '3000:3000'
      - '3001:3001'
      - '8000:8000'
      - '80:80'
      - '443:443'
    stdin_open: true
    tty: true
